### ISSUE TITLE
/mines auto does not work

### ISSUE THREAD

**Issue by refaim** [refaim/AutoDB2#2]
xxx: hey hope you don't mind me messaging you
xxx: it looks like AutoDB 2.0 doesn't work with "mines auto"
xxx: just "mines"works but not with auto
xxx: I tried disabling any other addon than pfQuest and AutoDB, but it gives the same issue
xxx: could it have something to do with not knowing the skill level yet at load? Or something in pfQuest not being ready yet? do you think it can be delayed somehow?

**Comment by Rahnd2137** [comment]
It worked for me, did you use "/autodb mines" ?

**Comment by refaim** [comment]
Worked for me too, I used `/autodb add mines auto`

**Comment by blehz-be** [comment]
I retested it with a clean Addons and empty WTF folder.
It kind of works (now), but only shows copper nodes while it should show up to iron nodes. When running it manually it does work.

**Comment by refaim** [comment]
> I retested it with a clean Addons and empty WTF folder. It kind of works (now), but only shows copper nodes while it should show up to iron nodes. When running it manually it does work.

That's weird. I tested and saw copper and tin. Did you try to re-enter the game world or reload interface?

**Comment by blehz-be** [comment]
> 

I login to my character, add the command with "/autodb add mines auto" -> this also runs it, which works
--> this actually opens the map on a zone different than the zone I am in? Which is also weird to me? Does it do that for you too? It used to be Ashenvale, now it's Arathi Highlands.
Then I logout and login again on the same character -> only shows Copper nodes as far as I can see.
Run it manually -> shows only Iron nodes (I'm at mining skill 146).

**Comment by blehz-be** [comment]
I added this small debug function to the RunAutoexec function (inside the if) and the HandlePrintCommand function at the top.
It prints 0 in the function, but works in the list function.

So the skill info is not yet loaded it seems.
Can this hook in or wait for pfQuest or whatever is needed in the WoW API to get initialized?

```
local function PrintSkills()
    AutoDB.info("Skills: " .. GetNumSkillLines())
    for i=0,GetNumSkillLines() do
        local skillName, _, _, skillRank = GetSkillLineInfo(i)
        if skillName ~= nil then
            AutoDB.info("Skill " .. skillName .. "rank: " .. skillRank)
        end
    end
end
```

**Comment by refaim** [comment]
@blehz-be thanks a lot! Your research has been very helpful. I fixed the issue, please try the new version.

**Comment by blehz-be** [comment]
That's fixed, thank you!
